language: erlang

otp_release:
  - 21.3.7
  - 20.2
  - 20.1
  - 20.1
  - 19.3
  - 19.2
  - 19.1
  - 19.0
  - 18.3
  - 18.2.1
  - 18.1
  - 18.0

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

script: "make travis"
